version: '3.8'

networks:
  gymapp-network:
    driver: bridge

volumes:
  sqlserver-data:
    driver: local

services:
  db:
    container_name: gymapp-db
    image: mcr.microsoft.com/mssql/server:2019-CU30-ubuntu-20.04
    ports:
      - "1433:1433"
    networks:
      - gymapp-network
    volumes:
      - sqlserver-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    restart: always

  api:
    container_name: gymapp-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    networks:
      - gymapp-network
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__GymappDB=Server=db;Database=GymappDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:80;https://+:443
      # Configurar CORS para permitir solicitudes desde el frontend
      - AllowedOrigins=http://localhost:8080
    restart: always